# Generated by Django 4.0.3 on 2022-07-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_num', models.IntegerField(max_length=30, verbose_name='Class Number')),
                ('strength', models.IntegerField(max_length=30, verbose_name='Strength')),
                ('subjects', models.CharField(max_length=300, verbose_name='Subjects')),
            ],
        ),
    ]
