# Generated by Django 4.0.3 on 2022-07-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='id',
        ),
        migrations.AlterField(
            model_name='class',
            name='class_num',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Class Number'),
        ),
        migrations.AlterField(
            model_name='class',
            name='strength',
            field=models.IntegerField(verbose_name='Strength'),
        ),
    ]
