# Generated by Django 4.0.3 on 2022-07-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_remove_class_id_alter_class_class_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('subject', models.CharField(max_length=100, verbose_name='Name')),
                ('class_num', models.IntegerField(verbose_name='Class')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
