# Generated by Django 4.0.3 on 2022-07-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Subject'),
        ),
    ]
