# Generated by Django 4.0.3 on 2022-07-03 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_alter_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='sections',
            field=models.IntegerField(default=3, verbose_name='Sections'),
        ),
    ]
